# Generated by Django 3.2.2 on 2021-09-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pills',
        ),
    ]
