# Generated by Django 3.2.6 on 2021-09-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210904_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='pills',
        ),
    ]
