# Generated by Django 3.2.6 on 2021-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_profilemodel_pills'),
    ]

    operations = [
        migrations.AddField(
            model_name='medmodel',
            name='pill_dosage',
            field=models.IntegerField(default=0),
        ),
    ]
