# Generated by Django 3.2.7 on 2021-09-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_medmodel_pill_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.IntegerField(default=-1),
        ),
    ]
